"""
Italian translations
"""

translations = {
    "Create Server": "Crea Server",
    "Start": "Avvia",
    "Settings": "Impostazioni",
    "Console": "Terminale",
    "Edit server settings": "Modifica impostazioni",
    "Edit server properties": "Modifica proprietà",
    "Delete server": "Elimina server",
    "Your servers": "I tuoi server",
    "Seems like you don't have any. Let's create one!": "Sembra tu non ne abbia. Creane uno!",
    "Save": "Salva",
    "Starting": "Avviando",
    "Stopping": "Stoppando",
    "Running": "In esecuzione",
    "Stopped": "Spento",
    "Invalid server": "Server invalido",
    "Write command": "Scrivi comando",
    "Status: {value}": "Stato: {value}",
    "Starting creation of server {name}": "Avvio creazione server {name}",
    "Server name can't be empty": "Il nome del server non può essere vuoto",
    "Server created!": "Server creato!",
    "New Server": "Nuovo Server",
    "Server name": "Nome del server",
    "Accept EULA (Required)": "Accetta EULA (Richiesto)",
    "Dedicated RAM": "RAM dedicata",
    "Other settings": "Altre impostazioni",
    "Server Type": "Tipo di server",
    "Server Version": "Versione del server",
    "Cancel": "Annulla",
    "Create": "Crea",
    "Version URL not found": "URL versione non trovato",
    "Saving settings of server '{name}'": "Salvataggio impostazioni del server '{name}'",
    "Settings saved!": "Impostazioni salvate!",
    "Edit Server": "Modifica Server",
    "Too long!": "Troppo lungo!",
    "Suggested for this device: {value} GB": "Suggerito per questo dispositivo: {value} GB",
    "Deleting server {name}": "Eliminazione server {name}",
    "Server deleted": "Server eliminato",
    "Are you sure?": "Sei sicuro?",
    "Write '{name}' below to confirm": "Scrivi '{name}' qui sotto per confermare",
    "Confirm name": "Conferma nome",
    "Wrong name": "Nome sbagliato",
    "Delete server folder": "Elimina cartella del server",
    "Delete": "Elimina",
    "Server version can't be empty": "La versione del server non può essere vuota",
    "Some settings require a restart to take effect. Please restart the app after changing them.": "Alcune impostazioni richiedono un riavvio per avere effetto. Si prega di riavviare l'app dopo averle cambiate.",
    "Close": "Chiudi",
    "Language": "Lingua",
    "Unsupported Forge Version. THIS IS NOT A BUG!" : "Versione di Forge non supportata. QUESTO NON È UN BUG!",
    "Creating server {name}" : "Creazione server {name}",
    "Open server folder": "Apri cartella del server",
    "RAM usage": "Utilizzo RAM",
    "CPU usage": "Utilizzo CPU",
    "Disk read": "Lettura disco",
    "Disk write": "Scrittura disco",
    "Back": "Indietro",
}
